#if defined(UIPC_COREX_CUDA10_COMPAT) && UIPC_COREX_CUDA10_COMPAT

// > Squared Version
// > D := d*d

#if defined(UIPC_COREX_CUDA10_COMPAT) && UIPC_COREX_CUDA10_COMPAT && \
    !(defined(UIPC_FLOAT_SCALAR) && UIPC_FLOAT_SCALAR)
namespace corex_barrier_detail {

// Manual log(x) using the identity:
//   log(x) = 2 * atanh((x-1)/(x+1))
// with range reduction x = val * 2^n so that val in [0.5, 2).
template <typename T>
__host__ __device__ T safe_log(T x)
{
    if(x <= T(0)) return T(-1e30);

    T val = x;
    int n = 0;
    while(val > T(2))  { val *= T(0.5); ++n; }
    while(val < T(0.5)) { val *= T(2);  --n; }

    T u = (val - T(1)) / (val + T(1));
    T u2 = u * u;
    T sum = u;
    T uk = u;
    uk *= u2; sum += uk / T(3);
    uk *= u2; sum += uk / T(5);
    uk *= u2; sum += uk / T(7);
    uk *= u2; sum += uk / T(9);
    uk *= u2; sum += uk / T(11);
    uk *= u2; sum += uk / T(13);
    uk *= u2; sum += uk / T(15);

    constexpr T ln2 = T(0.6931471805599453);
    return T(2) * sum + T(n) * ln2;
}

// Compute log(a/b) = safe_log(a) - safe_log(b) without forming a/b,
// avoiding catastrophic precision loss on CoreX for small-number division.
template <typename T>
__host__ __device__ T safe_log_ratio(T a, T b)
{
    return safe_log(a) - safe_log(b);
}

template <typename T>
__host__ __device__ void barrier_terms(const T& D_in,
                                       const T& dHat,
                                       const T& xi,
                                       T&       s,
                                       T&       V,
                                       T&       diff,
                                       T&       log_ratio)
{
    const T xi2 = xi * xi;
    s           = D_in - xi2;
    V           = dHat * dHat + T(2) * dHat * xi;
    if(s < V * T(1e-3)) s = V * T(1e-3);
    if(s > V * T(0.999)) s = V * T(0.999);
    diff      = s - V;
    log_ratio = safe_log_ratio(s, V);
}

}  // namespace corex_barrier_detail
#endif

template <typename T>
__host__ __device__ void KappaBarrier(T& R, const T& kappa, const T& D_in, const T& dHat, const T& xi)
{
#if defined(UIPC_COREX_CUDA10_COMPAT) && UIPC_COREX_CUDA10_COMPAT && \
    !(defined(UIPC_FLOAT_SCALAR) && UIPC_FLOAT_SCALAR)
    // Original: B(D) = -kappa * (D - xi^2 - V)^2 * log((D - xi^2) / V)
    // where V = dHat^2 + 2*dHat*xi = (dHat+xi)^2 - xi^2.
    // Use safe_log_ratio to avoid forming the small-number quotient directly.
    T s, V, diff, log_ratio;
    corex_barrier_detail::barrier_terms(D_in, dHat, xi, s, V, diff, log_ratio);
    R = -kappa * diff * diff * log_ratio;
#else
auto D = D_in;
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = std::pow(dHat, 2) + 2*dHat*xi;
/* Simplified Expr */
R = -kappa*std::pow(D - x0 - x1, 2)*log((D - x0)/x1);
#endif
}
template <typename T>
__host__ __device__ void dKappaBarrierdD(T& R, const T& kappa, const T& D_in, const T& dHat, const T& xi)
{
#if defined(UIPC_COREX_CUDA10_COMPAT) && UIPC_COREX_CUDA10_COMPAT && \
    !(defined(UIPC_FLOAT_SCALAR) && UIPC_FLOAT_SCALAR)
    // GPU_IPC-style analytic barrier derivative. This removes the nested
    // central difference from the CoreX compatibility path.
    T s, V, diff, log_ratio;
    corex_barrier_detail::barrier_terms(D_in, dHat, xi, s, V, diff, log_ratio);
    R = -kappa * T(2) * diff * log_ratio - kappa * diff * diff / s;
#else
auto D = D_in;
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = D - x0;
auto x2 = std::pow(dHat, 2);
auto x3 = dHat*xi;
auto x4 = x2 + 2*x3;
/* Simplified Expr */
R = -kappa*(2*D - 2*x0 - 2*x2 - 4*x3)*log(x1/x4) - kappa*std::pow(D - x0 - x4, 2)/x1;
#endif
}
template <typename T>
__host__ __device__ void ddKappaBarrierddD(T& R, const T& kappa, const T& D_in, const T& dHat, const T& xi)
{
#if defined(UIPC_COREX_CUDA10_COMPAT) && UIPC_COREX_CUDA10_COMPAT && \
    !(defined(UIPC_FLOAT_SCALAR) && UIPC_FLOAT_SCALAR)
    // Analytic second derivative of the same clamped shifted barrier domain.
    T s, V, diff, log_ratio;
    corex_barrier_detail::barrier_terms(D_in, dHat, xi, s, V, diff, log_ratio);
    R = kappa * diff * diff / (s * s) - T(2) * kappa * log_ratio
        - T(4) * kappa * diff / s;
#else
auto D = D_in;
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = D - x0;
auto x2 = std::pow(dHat, 2);
auto x3 = dHat*xi;
auto x4 = x2 + 2*x3;
auto x5 = 2*kappa;
/* Simplified Expr */
R = kappa*std::pow(D - x0 - x4, 2)/std::pow(x1, 2) - x5*log(x1/x4) - x5*(2*D - 2*x0 - 2*x2 - 4*x3)/x1;
#endif
}
#else

// > Squared Version
// > D := d*d

template <typename T>
__host__ __device__ void KappaBarrier(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
/*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2} \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = std::pow(dHat, 2) + 2*dHat*xi;
/* Simplified Expr */
R = -kappa*std::pow(D - x0 - x1, 2)*log((D - x0)/x1);
}
template <typename T>
__host__ __device__ void dKappaBarrierdD(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
/*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right) \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)} - \frac{\kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2}}{D - \xi^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = D - x0;
auto x2 = std::pow(dHat, 2);
auto x3 = dHat*xi;
auto x4 = x2 + 2*x3;
/* Simplified Expr */
R = -kappa*(2*D - 2*x0 - 2*x2 - 4*x3)*log(x1/x4) - kappa*std::pow(D - x0 - x4, 2)/x1;
}
template <typename T>
__host__ __device__ void ddKappaBarrierddD(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
/*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - 2 \kappa \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)} - \frac{2 \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right)}{D - \xi^{2}} + \frac{\kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2}}{\left(D - \xi^{2}\right)^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
/* Sub Exprs */
auto x0 = std::pow(xi, 2);
auto x1 = D - x0;
auto x2 = std::pow(dHat, 2);
auto x3 = dHat*xi;
auto x4 = x2 + 2*x3;
auto x5 = 2*kappa;
/* Simplified Expr */
R = kappa*std::pow(D - x0 - x4, 2)/std::pow(x1, 2) - x5*log(x1/x4) - x5*(2*D - 2*x0 - 2*x2 - 4*x3)/x1;
}
#endif
